# Generated by Django 4.0.4 on 2022-06-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='If_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField()),
                ('major', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rigth_away', models.IntegerField()),
                ('lie_on_sied', models.IntegerField()),
                ('hug_blanket', models.IntegerField()),
                ('roll_around', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.IntegerField()),
                ('sea', models.IntegerField()),
                ('tree', models.IntegerField()),
                ('festival', models.IntegerField()),
                ('oasis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underground', models.IntegerField()),
                ('lakeside', models.IntegerField()),
                ('cave', models.IntegerField()),
                ('cabin', models.IntegerField()),
                ('open_field', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chicken', models.IntegerField()),
                ('cropple', models.IntegerField()),
                ('pork', models.IntegerField()),
                ('steak', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sns', models.IntegerField()),
                ('game', models.IntegerField()),
                ('cook', models.IntegerField()),
                ('movie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('pre_student', models.IntegerField()),
                ('remainder', models.IntegerField()),
            ],
        ),
    ]
