# Generated by Django 4.0.5 on 2022-06-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_result_question6'),
        ('pages', '0004_result_nickname_alter_result_question6'),
    ]

    operations = [
    ]
