# Generated by Django 4.0.5 on 2022-06-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_merge_20220604_1440'),
        ('pages', '0006_remove_result_question1_remove_result_question2_and_more'),
    ]

    operations = [
    ]
